spring.application.name=dispatcher-sms
spring.config.import=optional:file:.env[.properties],optional:file:../../.env[.properties]

twilio.account-sid=${TWILIO_ACCOUNT_SID:mock_twilio_sid}
twilio.auth-token=${TWILIO_AUTH_TOKEN:mock_twilio_token}
twilio.phone-number=${TWILIO_PHONE_NUMBER:+15005550006}

spring.rabbitmq.listener.simple.retry.enabled=true

spring.rabbitmq.listener.simple.retry.max-retries=3

spring.rabbitmq.listener.simple.retry.initial-interval=2000ms
spring.rabbitmq.listener.simple.retry.multiplier=2.0
spring.rabbitmq.listener.simple.retry.max-interval=10000ms

spring.rabbitmq.listener.simple.default-requeue-rejected=false
