spring.application.name=dispatcher-sms

twilio.account.sid=<sid>
twilio.auth.token=<at>
twilio.phone.number=<pno>

spring.rabbitmq.listener.simple.retry.enabled=true

spring.rabbitmq.listener.simple.retry.max-retries=3

spring.rabbitmq.listener.simple.retry.initial-interval=2000ms
spring.rabbitmq.listener.simple.retry.multiplier=2.0
spring.rabbitmq.listener.simple.retry.max-interval=10000ms

spring.rabbitmq.listener.simple.default-requeue-rejected=false