spring.application.name=dispatcher-email
spring.config.import=optional:file:.env[.properties],optional:file:../../.env[.properties]

sendgrid.api-key=${SENDGRID_API_KEY:mock_sendgrid_key}
sendgrid.from.email=${SENDGRID_FROM_EMAIL:test@example.com}
sendgrid.from.name=${SENDGRID_FROM_NAME:MockSender}

spring.rabbitmq.listener.simple.retry.enabled=true

spring.rabbitmq.listener.simple.retry.max-retries=3

spring.rabbitmq.listener.simple.retry.initial-interval=2000ms
spring.rabbitmq.listener.simple.retry.multiplier=2.0
spring.rabbitmq.listener.simple.retry.max-interval=10000ms

spring.rabbitmq.listener.simple.default-requeue-rejected=false
